# Generated by Django 6.1.1 on 2026-10-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='code_mode',
            field=models.BooleanField(default=False),
        ),
    ]
