# Generated by Django 6.1.1 on 2026-09-29 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('conversations', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('provisioning', 'Provisioning'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timed_out', 'Timed Out')], db_index=True, default='queued', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('permissions', models.JSONField()),
                ('tools', models.JSONField()),
                ('instructions', models.TextField(blank=True)),
                ('model_alias', models.CharField(max_length=64)),
                ('token_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('max_writes', models.PositiveIntegerField()),
                ('write_count', models.PositiveIntegerField(default=0)),
                ('writes_uncertain', models.BooleanField(default=False)),
                ('max_model_calls', models.PositiveIntegerField()),
                ('model_calls', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('event_seq', models.PositiveIntegerField(default=0)),
                ('worker_seq', models.PositiveIntegerField(default=0)),
                ('sandbox_provider', models.CharField(blank=True, max_length=32)),
                ('sandbox_handle', models.JSONField(blank=True, null=True)),
                ('sandbox_released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='agents.agent')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='conversations.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('status', 'Status'), ('phase', 'Phase'), ('text_delta', 'Text Delta'), ('tool_call', 'Tool Call'), ('message', 'Message')], max_length=32)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='runs.run')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='RunPageToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('tool', models.CharField(max_length=128)),
                ('query_hash', models.CharField(max_length=64)),
                ('upstream_cursor', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_tokens', to='runs.run')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunWrite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('uncertain', 'Uncertain')], default='pending', max_length=16)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writes', to='runs.run')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['status', 'created_at'], name='run_status_created'),
        ),
        migrations.AddConstraint(
            model_name='runevent',
            constraint=models.UniqueConstraint(fields=('run', 'seq'), name='run_event_seq_unique'),
        ),
        migrations.AddConstraint(
            model_name='runwrite',
            constraint=models.UniqueConstraint(fields=('run', 'key'), name='run_write_key_unique'),
        ),
    ]
