# Generated by Django 6.1.1 on 2026-09-29 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('conversations', '0002_initial'),
        ('runs', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'provisioning', 'running'])), fields=('conversation',), name='run_one_active_per_conversation'),
        ),
    ]
