# Generated by Django 6.1.1 on 2026-09-30 09:02

from django.db import migrations, models


def pending_to_uncertain(apps, schema_editor):
    """A pending write may or may not have reached the provider; its run must not write again."""
    RunWrite = apps.get_model("runs", "RunWrite")
    Run = apps.get_model("runs", "Run")
    pending = RunWrite.objects.filter(status="pending")
    Run.objects.filter(pk__in=pending.values("run_id")).update(writes_uncertain=True)
    pending.update(status="uncertain")


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_one_active_run_per_conversation'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(pending_to_uncertain, migrations.RunPython.noop),
        migrations.AddField(
            model_name='runwrite',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runwrite',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runwrite',
            name='status',
            field=models.CharField(choices=[('dispatched', 'Dispatched'), ('succeeded', 'Succeeded'), ('uncertain', 'Uncertain')], default='dispatched', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='runwrite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'dispatched')), fields=('run',), name='run_write_one_in_flight'),
        ),
    ]
