# Generated by Django 6.1.1 on 2026-09-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_write_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='unmetered_model_calls',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
