# Generated by Django 6.1.1 on 2026-10-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_tool_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='code_mode',
            field=models.BooleanField(default=False),
        ),
    ]
