# Generated by Django 6.1.1 on 2026-10-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_code_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='code_mode',
        ),
    ]
