# Generated by Django 6.1.1 on 2026-10-06 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0007_remove_run_code_mode'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='attempt',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='run',
            name='journal_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='journal_seq',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RunCommit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('attempt', models.PositiveIntegerField()),
                ('data', models.BinaryField()),
                ('key_version', models.CharField(max_length=32)),
                ('size', models.PositiveIntegerField()),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='runs.run')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'seq'), name='run_commit_seq_unique')],
            },
        ),
    ]
