# Generated by Django 6.1.1 on 2026-10-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0008_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='attempt_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Runs claimed before this field existed get the provisioning timeout from now.
        migrations.RunSQL(
            "UPDATE runs_run SET attempt_started_at = now() WHERE status IN ('provisioning', 'running')",
            migrations.RunSQL.noop,
        ),
    ]
