# Generated by Django 6.1.1 on 2026-10-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0009_attempt_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='max_model_calls',
        ),
        migrations.RemoveField(
            model_name='run',
            name='max_tool_calls',
        ),
        migrations.RemoveField(
            model_name='run',
            name='max_writes',
        ),
        migrations.RemoveField(
            model_name='run',
            name='write_count',
        ),
    ]
