# Generated by Django 6.1.1 on 2026-10-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0010_run_limits_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runevent',
            name='type',
            field=models.CharField(choices=[('status', 'Status'), ('phase', 'Phase'), ('text_delta', 'Text Delta'), ('reasoning_delta', 'Reasoning Delta'), ('tool_call', 'Tool Call'), ('message', 'Message')], max_length=32),
        ),
    ]
