# Generated by Django 6.1.1 on 2026-10-07 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('runs', '0011_reasoning_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='base_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='files.folderversion'),
        ),
        migrations.AddField(
            model_name='run',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='files.folderversion'),
        ),
        migrations.AddField(
            model_name='run',
            name='result_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='files.folderversion'),
        ),
        migrations.AddField(
            model_name='run',
            name='uploaded_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
