# Generated by Django 6.1.1 on 2026-10-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0012_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="folder_warnings",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="runevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("status", "Status"),
                    ("phase", "Phase"),
                    ("text_delta", "Text Delta"),
                    ("reasoning_delta", "Reasoning Delta"),
                    ("tool_call", "Tool Call"),
                    ("local_tool", "Local Tool"),
                    ("message", "Message"),
                ],
                max_length=32,
            ),
        ),
    ]
