# Generated by Django 6.1.1 on 2026-10-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0013_local_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='folder_changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
