# Generated by Django 6.1.1 on 2026-09-29 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('connections', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('ceiling', 'Ceiling'), ('user', 'User'), ('agent', 'Agent')], max_length=16)),
                ('restricted', models.BooleanField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('resource_kind', models.CharField(max_length=64)),
                ('resource_id', models.CharField(max_length=200)),
                ('actions', models.JSONField(default=list)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=8)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='connections.connection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='permissions.permissionlayer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='permissionlayer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', True), ('level', 'ceiling'), ('user__isnull', True)), models.Q(('agent__isnull', True), ('level', 'user'), ('user__isnull', False)), models.Q(('agent__isnull', False), ('level', 'agent'), ('user__isnull', True)), _connector='OR'), name='permission_layer_subject_matches_level'),
        ),
        migrations.AddConstraint(
            model_name='permissionlayer',
            constraint=models.UniqueConstraint(condition=models.Q(('level', 'ceiling')), fields=('workspace',), name='permission_layer_one_ceiling'),
        ),
        migrations.AddConstraint(
            model_name='permissionlayer',
            constraint=models.UniqueConstraint(condition=models.Q(('level', 'user')), fields=('workspace', 'user'), name='permission_layer_one_per_user'),
        ),
        migrations.AddConstraint(
            model_name='permissionlayer',
            constraint=models.UniqueConstraint(condition=models.Q(('level', 'agent')), fields=('agent',), name='permission_layer_one_per_agent'),
        ),
        migrations.AddConstraint(
            model_name='grant',
            constraint=models.UniqueConstraint(fields=('layer', 'connection', 'resource_kind', 'resource_id', 'effect'), name='grant_unique'),
        ),
    ]
