# Generated by Django 6.1.1 on 2026-09-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='resource_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
