# Generated by Django 6.1.1 on 2026-10-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_admissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosite',
            name='featured_suggestion',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
