// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthorizeData, AuthorizeResponses, CancelRunData, CancelRunResponses, ChangeAccessData, ChangeAccessResponses, ConnectKeyData, ConnectKeyResponses, CreateAgentData, CreateAgentResponses, CreateConversationData, CreateConversationResponses, DeleteAgentData, DeleteAgentResponses, DeleteConnectionData, DeleteConnectionResponses, DeleteConversationData, DeleteConversationResponses, DeleteUploadData, DeleteUploadResponses, DemoConfigData, DemoConfigResponses, DemoEmailData, DemoEmailResponses, DemoGateData, DemoGateResponses, EnableData, EnableResponses, GetAccessData, GetAccessResponses, GetAgentData, GetAgentResponses, GetConversationData, GetConversationResponses, GetRunData, GetRunResponses, ListAccessResourcesData, ListAccessResourcesResponses, ListAgentsData, ListAgentsResponses, ListConnectionsData, ListConnectionsResponses, ListConnectorsData, ListConnectorsResponses, ListConversationsData, ListConversationsResponses, ListFilesData, ListFilesResponses, MeData, MeResponses, PostMessageData, PostMessageResponses, ReconnectData, ReconnectResponses, ReplaceKeyData, ReplaceKeyResponses, UpdateAgentData, UpdateAgentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Demo Config
 */
export const demoConfig = <ThrowOnError extends boolean = false>(options?: Options<DemoConfigData, ThrowOnError>): RequestResult<DemoConfigResponses, unknown, ThrowOnError> => (options?.client ?? client).get<DemoConfigResponses, unknown, ThrowOnError>({ url: '/api/demo/config', ...options });

/**
 * Demo Email
 *
 * Creates a passwordless account for the address if there is none, so a sign-in code can be sent.
 *
 * Answers the same whether or not the account existed.
 */
export const demoEmail = <ThrowOnError extends boolean = false>(options: Options<DemoEmailData, ThrowOnError>): RequestResult<DemoEmailResponses, unknown, ThrowOnError> => (options.client ?? client).post<DemoEmailResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'csrftoken',
            type: 'apiKey'
        }],
    url: '/api/demo/email',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Demo Gate
 *
 * Admits this browser to sign in after a Turnstile check, and remembers the newsletter choice.
 */
export const demoGate = <ThrowOnError extends boolean = false>(options: Options<DemoGateData, ThrowOnError>): RequestResult<DemoGateResponses, unknown, ThrowOnError> => (options.client ?? client).post<DemoGateResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'csrftoken',
            type: 'apiKey'
        }],
    url: '/api/demo/gate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Me
 */
export const me = <ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>): RequestResult<MeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<MeResponses, unknown, ThrowOnError>({
    security: [{
            key: 'SessionAuth',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/me',
    ...options
});

/**
 * List Agents
 */
export const listAgents = <ThrowOnError extends boolean = false>(options: Options<ListAgentsData, ThrowOnError>): RequestResult<ListAgentsResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListAgentsResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/agents',
    ...options
});

/**
 * Create Agent
 */
export const createAgent = <ThrowOnError extends boolean = false>(options: Options<CreateAgentData, ThrowOnError>): RequestResult<CreateAgentResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateAgentResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/agents',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Agent
 */
export const deleteAgent = <ThrowOnError extends boolean = false>(options: Options<DeleteAgentData, ThrowOnError>): RequestResult<DeleteAgentResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteAgentResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/agents/{agent_id}',
    ...options
});

/**
 * Get Agent
 */
export const getAgent = <ThrowOnError extends boolean = false>(options: Options<GetAgentData, ThrowOnError>): RequestResult<GetAgentResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetAgentResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/agents/{agent_id}',
    ...options
});

/**
 * Update Agent
 */
export const updateAgent = <ThrowOnError extends boolean = false>(options: Options<UpdateAgentData, ThrowOnError>): RequestResult<UpdateAgentResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateAgentResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/agents/{agent_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Connections
 */
export const listConnections = <ThrowOnError extends boolean = false>(options: Options<ListConnectionsData, ThrowOnError>): RequestResult<ListConnectionsResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListConnectionsResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/connections',
    ...options
});

/**
 * Delete Connection
 */
export const deleteConnection = <ThrowOnError extends boolean = false>(options: Options<DeleteConnectionData, ThrowOnError>): RequestResult<DeleteConnectionResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteConnectionResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}',
    ...options
});

/**
 * Get Access
 *
 * What the user allows on this connection. Does not call the provider.
 */
export const getAccess = <ThrowOnError extends boolean = false>(options: Options<GetAccessData, ThrowOnError>): RequestResult<GetAccessResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetAccessResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}/access',
    ...options
});

/**
 * Change Access
 *
 * Changes what the user allows on some resources, all or nothing. Revokes the user's active runs.
 */
export const changeAccess = <ThrowOnError extends boolean = false>(options: Options<ChangeAccessData, ThrowOnError>): RequestResult<ChangeAccessResponses, unknown, ThrowOnError> => (options.client ?? client).patch<ChangeAccessResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}/access',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Access Resources
 *
 * One page of resources the connected account can see, with what the user allows on each.
 */
export const listAccessResources = <ThrowOnError extends boolean = false>(options: Options<ListAccessResourcesData, ThrowOnError>): RequestResult<ListAccessResourcesResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListAccessResourcesResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}/access/resources',
    ...options
});

/**
 * Replace Key
 *
 * Replaces the key of an API key connection with another key for the same account.
 */
export const replaceKey = <ThrowOnError extends boolean = false>(options: Options<ReplaceKeyData, ThrowOnError>): RequestResult<ReplaceKeyResponses, unknown, ThrowOnError> => (options.client ?? client).put<ReplaceKeyResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}/key',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reconnect
 *
 * Reconnects the account, or grants the provider access that allowed actions still need.
 */
export const reconnect = <ThrowOnError extends boolean = false>(options: Options<ReconnectData, ThrowOnError>): RequestResult<ReconnectResponses, unknown, ThrowOnError> => (options.client ?? client).post<ReconnectResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}/reconnect',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Authorize
 */
export const authorize = <ThrowOnError extends boolean = false>(options: Options<AuthorizeData, ThrowOnError>): RequestResult<AuthorizeResponses, unknown, ThrowOnError> => (options.client ?? client).post<AuthorizeResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/connections/{provider}/authorize',
    ...options
});

/**
 * Enable
 *
 * Adds a service this instance runs itself (the Web) to the user's connections. Allows nothing yet.
 */
export const enable = <ThrowOnError extends boolean = false>(options: Options<EnableData, ThrowOnError>): RequestResult<EnableResponses, unknown, ThrowOnError> => (options.client ?? client).post<EnableResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/connections/{provider}/enable',
    ...options
});

/**
 * Connect Key
 *
 * Connects an account with an API key. The key is checked with the provider and never returned.
 */
export const connectKey = <ThrowOnError extends boolean = false>(options: Options<ConnectKeyData, ThrowOnError>): RequestResult<ConnectKeyResponses, unknown, ThrowOnError> => (options.client ?? client).post<ConnectKeyResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/connections/{provider}/key',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Connectors
 */
export const listConnectors = <ThrowOnError extends boolean = false>(options: Options<ListConnectorsData, ThrowOnError>): RequestResult<ListConnectorsResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListConnectorsResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/connectors',
    ...options
});

/**
 * List Conversations
 */
export const listConversations = <ThrowOnError extends boolean = false>(options: Options<ListConversationsData, ThrowOnError>): RequestResult<ListConversationsResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListConversationsResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/conversations',
    ...options
});

/**
 * Create Conversation
 */
export const createConversation = <ThrowOnError extends boolean = false>(options: Options<CreateConversationData, ThrowOnError>): RequestResult<CreateConversationResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateConversationResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/conversations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Conversation
 */
export const deleteConversation = <ThrowOnError extends boolean = false>(options: Options<DeleteConversationData, ThrowOnError>): RequestResult<DeleteConversationResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteConversationResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/conversations/{conversation_id}',
    ...options
});

/**
 * Get Conversation
 */
export const getConversation = <ThrowOnError extends boolean = false>(options: Options<GetConversationData, ThrowOnError>): RequestResult<GetConversationResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetConversationResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/conversations/{conversation_id}',
    ...options
});

/**
 * List Files
 *
 * A version of the conversation's folder: the current one, or a run's base or result version.
 */
export const listFiles = <ThrowOnError extends boolean = false>(options: Options<ListFilesData, ThrowOnError>): RequestResult<ListFilesResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListFilesResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/conversations/{conversation_id}/files',
    ...options
});

/**
 * Post Message
 */
export const postMessage = <ThrowOnError extends boolean = false>(options: Options<PostMessageData, ThrowOnError>): RequestResult<PostMessageResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostMessageResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/conversations/{conversation_id}/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Run
 */
export const getRun = <ThrowOnError extends boolean = false>(options: Options<GetRunData, ThrowOnError>): RequestResult<GetRunResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetRunResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/runs/{run_id}',
    ...options
});

/**
 * Cancel Run
 */
export const cancelRun = <ThrowOnError extends boolean = false>(options: Options<CancelRunData, ThrowOnError>): RequestResult<CancelRunResponses, unknown, ThrowOnError> => (options.client ?? client).post<CancelRunResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/runs/{run_id}/cancel',
    ...options
});

/**
 * Delete Upload
 *
 * Removes an upload that was not attached; its file is deleted with the next sweep.
 */
export const deleteUpload = <ThrowOnError extends boolean = false>(options: Options<DeleteUploadData, ThrowOnError>): RequestResult<DeleteUploadResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteUploadResponses, unknown, ThrowOnError>({
    security: [{
            key: 'WorkspaceMember',
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/api/workspaces/{workspace_id}/uploads/{upload_id}',
    ...options
});
