// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * AccessChangesIn
 */
export type AccessChangesIn = {
    /**
     * Changes
     */
    changes: Array<ChangeIn>;
};

/**
 * AccessOut
 */
export type AccessOut = {
    /**
     * Actions
     */
    actions: Array<ActionOut>;
    connection: ConnectionOut;
    /**
     * Grants
     */
    grants: Array<GrantOut>;
    /**
     * Kinds
     */
    kinds: Array<KindOut>;
};

/**
 * ActionOut
 */
export type ActionOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Requires
     */
    requires: string | null;
};

/**
 * AgentIn
 */
export type AgentIn = {
    /**
     * Code Mode
     */
    code_mode?: boolean;
    /**
     * Connection Ids
     */
    connection_ids?: Array<string>;
    /**
     * Instructions
     */
    instructions?: string;
    /**
     * Name
     */
    name: string;
};

/**
 * AgentOut
 */
export type AgentOut = {
    /**
     * Can Edit
     */
    can_edit: boolean;
    /**
     * Code Mode
     */
    code_mode: boolean;
    /**
     * Connection Ids
     */
    connection_ids: Array<string>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Instructions
     */
    instructions: string;
    /**
     * Name
     */
    name: string;
};

/**
 * AllowedOut
 *
 * One action the user allows on the connection, and where.
 */
export type AllowedOut = {
    /**
     * Action
     */
    action: string;
    /**
     * Action Label
     */
    action_label: string;
    /**
     * All
     */
    all: boolean;
    /**
     * Count
     */
    count: number;
    /**
     * Kind
     */
    kind: string;
    /**
     * Kind Label
     */
    kind_label: string;
    /**
     * Names
     */
    names: Array<string>;
};

/**
 * AuthorizeOut
 */
export type AuthorizeOut = {
    /**
     * Url
     */
    url: string;
};

/**
 * ChangeIn
 */
export type ChangeIn = {
    /**
     * Actions
     */
    actions: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: string;
};

/**
 * ConnectionOut
 */
export type ConnectionOut = {
    /**
     * Allowed
     */
    allowed: Array<AllowedOut>;
    /**
     * Auth
     */
    auth: 'oauth2' | 'api_key' | 'builtin';
    /**
     * Consent Needed
     */
    consent_needed: Array<string>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Manage Label
     */
    manage_label: string | null;
    /**
     * Manage Url
     */
    manage_url: string | null;
    /**
     * Personal
     */
    personal: boolean;
    /**
     * Provider
     */
    provider: string;
    /**
     * Provider Name
     */
    provider_name: string;
    /**
     * Status
     */
    status: 'active' | 'error' | 'revoked';
};

/**
 * ConnectorOut
 */
export type ConnectorOut = {
    /**
     * Actions
     */
    actions: Array<ActionOut>;
    /**
     * Auth
     */
    auth: 'oauth2' | 'api_key' | 'builtin';
    /**
     * Key Hint
     */
    key_hint: string | null;
    /**
     * Key Label
     */
    key_label: string | null;
    /**
     * Kinds
     */
    kinds: Array<KindOut>;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
};

/**
 * ConsentIn
 */
export type ConsentIn = {
    /**
     * Actions
     */
    actions?: Array<string>;
};

/**
 * ConversationDetail
 */
export type ConversationDetail = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * Messages
     */
    messages: Array<MessageOut>;
    /**
     * Runs
     */
    runs: Array<RunOut>;
    /**
     * Title
     */
    title: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ConversationIn
 */
export type ConversationIn = {
    /**
     * Agent Id
     */
    agent_id: string;
};

/**
 * ConversationOut
 */
export type ConversationOut = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DemoConfigOut
 */
export type DemoConfigOut = {
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Providers
     */
    providers: Array<string>;
    /**
     * Turnstile Site Key
     */
    turnstile_site_key: string | null;
};

/**
 * DemoOut
 *
 * Present on a public demo instance. `visitor` is false for the people who run the demo.
 */
export type DemoOut = {
    /**
     * Chat Retention Hours
     */
    chat_retention_hours: number;
    /**
     * Featured Suggestion
     */
    featured_suggestion: string | null;
    /**
     * Suggestions
     */
    suggestions: Array<string>;
    /**
     * Turns Left
     */
    turns_left: number;
    /**
     * Turns Per Day
     */
    turns_per_day: number;
    /**
     * Visitor
     */
    visitor: boolean;
};

/**
 * EmailIn
 */
export type EmailIn = {
    /**
     * Email
     */
    email: string;
};

/**
 * EventOut
 */
export type EventOut = {
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * Seq
     */
    seq: number;
    /**
     * Type
     */
    type: 'status' | 'phase' | 'text_delta' | 'tool_call' | 'message';
};

/**
 * GateIn
 */
export type GateIn = {
    /**
     * Newsletter
     */
    newsletter: boolean;
    /**
     * Token
     */
    token: string;
};

/**
 * GrantOut
 */
export type GrantOut = {
    /**
     * Actions
     */
    actions: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Name
     */
    name: string | null;
};

/**
 * KeyIn
 */
export type KeyIn = {
    /**
     * Key
     */
    key: string;
};

/**
 * KindOut
 */
export type KindOut = {
    /**
     * Actions
     */
    actions: Array<string>;
    /**
     * Browsable
     */
    browsable: boolean;
    /**
     * Hierarchical
     */
    hierarchical: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Listed
     */
    listed: boolean;
    /**
     * Note
     */
    note: string | null;
    /**
     * Wildcard
     */
    wildcard: boolean;
};

/**
 * MeOut
 */
export type MeOut = {
    demo: DemoOut | null;
    user: UserOut;
    /**
     * Workspaces
     */
    workspaces: Array<WorkspaceOut>;
};

/**
 * MessageIn
 */
export type MessageIn = {
    /**
     * Content
     */
    content: string;
};

/**
 * MessageOut
 */
export type MessageOut = {
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: 'user' | 'assistant';
    /**
     * Run Id
     */
    run_id: string | null;
};

/**
 * PostedOut
 */
export type PostedOut = {
    message: MessageOut;
    run: RunOut;
};

/**
 * ResourceOut
 */
export type ResourceOut = {
    /**
     * Actions
     */
    actions: Array<string>;
    /**
     * Expandable
     */
    expandable: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Inherited
     */
    inherited: Array<string>;
    /**
     * Name
     */
    name: string;
};

/**
 * ResourcePageOut
 */
export type ResourcePageOut = {
    /**
     * Items
     */
    items: Array<ResourceOut>;
    /**
     * Next Cursor
     */
    next_cursor: string | null;
};

/**
 * ResourceQuery
 */
export type ResourceQuery = {
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Kind
     */
    kind: string;
    /**
     * Parent
     */
    parent?: string | null;
    /**
     * Q
     */
    q?: string | null;
};

/**
 * RunOut
 */
export type RunOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error Message
     */
    error_message: string;
    /**
     * Events
     */
    events: Array<EventOut>;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'queued' | 'provisioning' | 'running' | 'completed' | 'failed' | 'cancelled' | 'timed_out';
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Staff
     */
    is_staff: boolean;
    /**
     * Name
     */
    name: string;
};

/**
 * WorkspaceOut
 */
export type WorkspaceOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: 'personal' | 'team';
    /**
     * Name
     */
    name: string;
    /**
     * Role
     */
    role: 'owner' | 'admin' | 'member';
};

export type DemoConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/demo/config';
};

export type DemoConfigResponses = {
    /**
     * OK
     */
    200: DemoConfigOut;
};

export type DemoConfigResponse = DemoConfigResponses[keyof DemoConfigResponses];

export type DemoEmailData = {
    body: EmailIn;
    path?: never;
    query?: never;
    url: '/api/demo/email';
};

export type DemoEmailResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DemoEmailResponse = DemoEmailResponses[keyof DemoEmailResponses];

export type DemoGateData = {
    body: GateIn;
    path?: never;
    query?: never;
    url: '/api/demo/gate';
};

export type DemoGateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DemoGateResponse = DemoGateResponses[keyof DemoGateResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeResponses = {
    /**
     * OK
     */
    200: MeOut;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type ListAgentsData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/agents';
};

export type ListAgentsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<AgentOut>;
};

export type ListAgentsResponse = ListAgentsResponses[keyof ListAgentsResponses];

export type CreateAgentData = {
    body: AgentIn;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/agents';
};

export type CreateAgentResponses = {
    /**
     * Created
     */
    201: AgentOut;
};

export type CreateAgentResponse = CreateAgentResponses[keyof CreateAgentResponses];

export type DeleteAgentData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/agents/{agent_id}';
};

export type DeleteAgentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAgentResponse = DeleteAgentResponses[keyof DeleteAgentResponses];

export type GetAgentData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/agents/{agent_id}';
};

export type GetAgentResponses = {
    /**
     * OK
     */
    200: AgentOut;
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type UpdateAgentData = {
    body: AgentIn;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/agents/{agent_id}';
};

export type UpdateAgentResponses = {
    /**
     * OK
     */
    200: AgentOut;
};

export type UpdateAgentResponse = UpdateAgentResponses[keyof UpdateAgentResponses];

export type ListConnectionsData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections';
};

export type ListConnectionsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<ConnectionOut>;
};

export type ListConnectionsResponse = ListConnectionsResponses[keyof ListConnectionsResponses];

export type DeleteConnectionData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}';
};

export type DeleteConnectionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteConnectionResponse = DeleteConnectionResponses[keyof DeleteConnectionResponses];

export type GetAccessData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}/access';
};

export type GetAccessResponses = {
    /**
     * OK
     */
    200: AccessOut;
};

export type GetAccessResponse = GetAccessResponses[keyof GetAccessResponses];

export type ChangeAccessData = {
    body: AccessChangesIn;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}/access';
};

export type ChangeAccessResponses = {
    /**
     * OK
     */
    200: AccessOut;
};

export type ChangeAccessResponse = ChangeAccessResponses[keyof ChangeAccessResponses];

export type ListAccessResourcesData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query: {
        /**
         * Kind
         */
        kind: string;
        /**
         * Q
         */
        q?: string | null;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Parent
         */
        parent?: string | null;
    };
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}/access/resources';
};

export type ListAccessResourcesResponses = {
    /**
     * OK
     */
    200: ResourcePageOut;
};

export type ListAccessResourcesResponse = ListAccessResourcesResponses[keyof ListAccessResourcesResponses];

export type ReplaceKeyData = {
    body: KeyIn;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}/key';
};

export type ReplaceKeyResponses = {
    /**
     * OK
     */
    200: ConnectionOut;
};

export type ReplaceKeyResponse = ReplaceKeyResponses[keyof ReplaceKeyResponses];

export type ReconnectData = {
    body: ConsentIn;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}/reconnect';
};

export type ReconnectResponses = {
    /**
     * OK
     */
    200: AuthorizeOut;
};

export type ReconnectResponse = ReconnectResponses[keyof ReconnectResponses];

export type AuthorizeData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Provider
         */
        provider: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections/{provider}/authorize';
};

export type AuthorizeResponses = {
    /**
     * OK
     */
    200: AuthorizeOut;
};

export type AuthorizeResponse = AuthorizeResponses[keyof AuthorizeResponses];

export type EnableData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Provider
         */
        provider: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections/{provider}/enable';
};

export type EnableResponses = {
    /**
     * OK
     */
    200: ConnectionOut;
};

export type EnableResponse = EnableResponses[keyof EnableResponses];

export type ConnectKeyData = {
    body: KeyIn;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Provider
         */
        provider: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections/{provider}/key';
};

export type ConnectKeyResponses = {
    /**
     * OK
     */
    200: ConnectionOut;
};

export type ConnectKeyResponse = ConnectKeyResponses[keyof ConnectKeyResponses];

export type ListConnectorsData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connectors';
};

export type ListConnectorsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<ConnectorOut>;
};

export type ListConnectorsResponse = ListConnectorsResponses[keyof ListConnectorsResponses];

export type ListConversationsData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/conversations';
};

export type ListConversationsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<ConversationOut>;
};

export type ListConversationsResponse = ListConversationsResponses[keyof ListConversationsResponses];

export type CreateConversationData = {
    body: ConversationIn;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/conversations';
};

export type CreateConversationResponses = {
    /**
     * Created
     */
    201: ConversationOut;
};

export type CreateConversationResponse = CreateConversationResponses[keyof CreateConversationResponses];

export type DeleteConversationData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/conversations/{conversation_id}';
};

export type DeleteConversationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteConversationResponse = DeleteConversationResponses[keyof DeleteConversationResponses];

export type GetConversationData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/conversations/{conversation_id}';
};

export type GetConversationResponses = {
    /**
     * OK
     */
    200: ConversationDetail;
};

export type GetConversationResponse = GetConversationResponses[keyof GetConversationResponses];

export type PostMessageData = {
    body: MessageIn;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/conversations/{conversation_id}/messages';
};

export type PostMessageResponses = {
    /**
     * Created
     */
    201: PostedOut;
};

export type PostMessageResponse = PostMessageResponses[keyof PostMessageResponses];

export type GetRunData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/runs/{run_id}';
};

export type GetRunResponses = {
    /**
     * OK
     */
    200: RunOut;
};

export type GetRunResponse = GetRunResponses[keyof GetRunResponses];

export type CancelRunData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/runs/{run_id}/cancel';
};

export type CancelRunResponses = {
    /**
     * OK
     */
    200: RunOut;
};

export type CancelRunResponse = CancelRunResponses[keyof CancelRunResponses];
