// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * AccessIn
 */
export type AccessIn = {
    /**
     * Resources
     */
    resources: Array<ResourceAccessIn>;
};

/**
 * AccessOut
 */
export type AccessOut = {
    /**
     * Actions
     */
    actions: Array<ActionOut>;
    connection: ConnectionOut;
    /**
     * Resources
     */
    resources: Array<ResourceAccess>;
    /**
     * Scope Label
     */
    scope_label: string;
};

/**
 * ActionOut
 */
export type ActionOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Requires
     */
    requires: string | null;
};

/**
 * AgentIn
 */
export type AgentIn = {
    /**
     * Connection Ids
     */
    connection_ids?: Array<string>;
    /**
     * Instructions
     */
    instructions?: string;
    /**
     * Name
     */
    name: string;
};

/**
 * AgentOut
 */
export type AgentOut = {
    /**
     * Can Edit
     */
    can_edit: boolean;
    /**
     * Connection Ids
     */
    connection_ids: Array<string>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Instructions
     */
    instructions: string;
    /**
     * Name
     */
    name: string;
};

/**
 * AuthorizeOut
 */
export type AuthorizeOut = {
    /**
     * Url
     */
    url: string;
};

/**
 * ConnectionOut
 */
export type ConnectionOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Personal
     */
    personal: boolean;
    /**
     * Provider
     */
    provider: string;
    /**
     * Provider Name
     */
    provider_name: string;
    /**
     * Status
     */
    status: 'active' | 'error' | 'revoked';
};

/**
 * ConnectorOut
 */
export type ConnectorOut = {
    /**
     * Actions
     */
    actions: Array<ActionOut>;
    /**
     * Name
     */
    name: string;
    /**
     * Scope Label
     */
    scope_label: string;
    /**
     * Slug
     */
    slug: string;
};

/**
 * ConversationDetail
 */
export type ConversationDetail = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * Messages
     */
    messages: Array<MessageOut>;
    /**
     * Runs
     */
    runs: Array<RunOut>;
    /**
     * Title
     */
    title: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ConversationIn
 */
export type ConversationIn = {
    /**
     * Agent Id
     */
    agent_id: string;
};

/**
 * ConversationOut
 */
export type ConversationOut = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * EventOut
 */
export type EventOut = {
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
    /**
     * Seq
     */
    seq: number;
    /**
     * Type
     */
    type: 'status' | 'phase' | 'text_delta' | 'tool_call' | 'message';
};

/**
 * MeOut
 */
export type MeOut = {
    user: UserOut;
    /**
     * Workspaces
     */
    workspaces: Array<WorkspaceOut>;
};

/**
 * MessageIn
 */
export type MessageIn = {
    /**
     * Content
     */
    content: string;
};

/**
 * MessageOut
 */
export type MessageOut = {
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: 'user' | 'assistant';
    /**
     * Run Id
     */
    run_id: string | null;
};

/**
 * PostedOut
 */
export type PostedOut = {
    message: MessageOut;
    run: RunOut;
};

/**
 * ResourceAccess
 */
export type ResourceAccess = {
    /**
     * Actions
     */
    actions: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * ResourceAccessIn
 */
export type ResourceAccessIn = {
    /**
     * Actions
     */
    actions: Array<string>;
    /**
     * Id
     */
    id: string;
};

/**
 * RunOut
 */
export type RunOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error Message
     */
    error_message: string;
    /**
     * Events
     */
    events: Array<EventOut>;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'queued' | 'provisioning' | 'running' | 'completed' | 'failed' | 'cancelled' | 'timed_out';
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Staff
     */
    is_staff: boolean;
    /**
     * Name
     */
    name: string;
};

/**
 * WorkspaceOut
 */
export type WorkspaceOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: 'personal' | 'team';
    /**
     * Name
     */
    name: string;
    /**
     * Role
     */
    role: 'owner' | 'admin' | 'member';
};

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeResponses = {
    /**
     * OK
     */
    200: MeOut;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type ListAgentsData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/agents';
};

export type ListAgentsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<AgentOut>;
};

export type ListAgentsResponse = ListAgentsResponses[keyof ListAgentsResponses];

export type CreateAgentData = {
    body: AgentIn;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/agents';
};

export type CreateAgentResponses = {
    /**
     * Created
     */
    201: AgentOut;
};

export type CreateAgentResponse = CreateAgentResponses[keyof CreateAgentResponses];

export type DeleteAgentData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/agents/{agent_id}';
};

export type DeleteAgentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAgentResponse = DeleteAgentResponses[keyof DeleteAgentResponses];

export type GetAgentData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/agents/{agent_id}';
};

export type GetAgentResponses = {
    /**
     * OK
     */
    200: AgentOut;
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type UpdateAgentData = {
    body: AgentIn;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/agents/{agent_id}';
};

export type UpdateAgentResponses = {
    /**
     * OK
     */
    200: AgentOut;
};

export type UpdateAgentResponse = UpdateAgentResponses[keyof UpdateAgentResponses];

export type ListConnectionsData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections';
};

export type ListConnectionsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<ConnectionOut>;
};

export type ListConnectionsResponse = ListConnectionsResponses[keyof ListConnectionsResponses];

export type DeleteConnectionData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}';
};

export type DeleteConnectionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteConnectionResponse = DeleteConnectionResponses[keyof DeleteConnectionResponses];

export type GetAccessData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}/access';
};

export type GetAccessResponses = {
    /**
     * OK
     */
    200: AccessOut;
};

export type GetAccessResponse = GetAccessResponses[keyof GetAccessResponses];

export type SetAccessData = {
    body: AccessIn;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections/{connection_id}/access';
};

export type SetAccessResponses = {
    /**
     * OK
     */
    200: AccessOut;
};

export type SetAccessResponse = SetAccessResponses[keyof SetAccessResponses];

export type AuthorizeData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Provider
         */
        provider: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connections/{provider}/authorize';
};

export type AuthorizeResponses = {
    /**
     * OK
     */
    200: AuthorizeOut;
};

export type AuthorizeResponse = AuthorizeResponses[keyof AuthorizeResponses];

export type ListConnectorsData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/connectors';
};

export type ListConnectorsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<ConnectorOut>;
};

export type ListConnectorsResponse = ListConnectorsResponses[keyof ListConnectorsResponses];

export type ListConversationsData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/conversations';
};

export type ListConversationsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<ConversationOut>;
};

export type ListConversationsResponse = ListConversationsResponses[keyof ListConversationsResponses];

export type CreateConversationData = {
    body: ConversationIn;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/conversations';
};

export type CreateConversationResponses = {
    /**
     * Created
     */
    201: ConversationOut;
};

export type CreateConversationResponse = CreateConversationResponses[keyof CreateConversationResponses];

export type DeleteConversationData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/conversations/{conversation_id}';
};

export type DeleteConversationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteConversationResponse = DeleteConversationResponses[keyof DeleteConversationResponses];

export type GetConversationData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/conversations/{conversation_id}';
};

export type GetConversationResponses = {
    /**
     * OK
     */
    200: ConversationDetail;
};

export type GetConversationResponse = GetConversationResponses[keyof GetConversationResponses];

export type PostMessageData = {
    body: MessageIn;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/conversations/{conversation_id}/messages';
};

export type PostMessageResponses = {
    /**
     * Created
     */
    201: PostedOut;
};

export type PostMessageResponse = PostMessageResponses[keyof PostMessageResponses];

export type GetRunData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/runs/{run_id}';
};

export type GetRunResponses = {
    /**
     * OK
     */
    200: RunOut;
};

export type GetRunResponse = GetRunResponses[keyof GetRunResponses];

export type CancelRunData = {
    body?: never;
    path: {
        /**
         * Workspace Id
         */
        workspace_id: string;
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/workspaces/{workspace_id}/runs/{run_id}/cancel';
};

export type CancelRunResponses = {
    /**
     * OK
     */
    200: RunOut;
};

export type CancelRunResponse = CancelRunResponses[keyof CancelRunResponses];
