/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as LoginCodeRouteImport } from './routes/login_.code'
import { Route as LoginMfaRouteImport } from './routes/login_.mfa'
import { Route as WWorkspaceIdRouteImport } from './routes/w.$workspaceId'
import { Route as WWorkspaceIdIndexRouteImport } from './routes/w.$workspaceId.index'
import { Route as WWorkspaceIdAccountRouteImport } from './routes/w.$workspaceId.account'
import { Route as WWorkspaceIdAgentsRouteImport } from './routes/w.$workspaceId.agents'
import { Route as WWorkspaceIdChatRouteImport } from './routes/w.$workspaceId.chat'
import { Route as WWorkspaceIdConnectionsRouteImport } from './routes/w.$workspaceId.connections'
import { Route as WWorkspaceIdChatIndexRouteImport } from './routes/w.$workspaceId.chat.index'
import { Route as WWorkspaceIdChatConversationIdRouteImport } from './routes/w.$workspaceId.chat.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCodeRoute = LoginCodeRouteImport.update({
  id: '/login_/code',
  path: '/login/code',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginMfaRoute = LoginMfaRouteImport.update({
  id: '/login_/mfa',
  path: '/login/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdRoute = WWorkspaceIdRouteImport.update({
  id: '/w/$workspaceId',
  path: '/w/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdIndexRoute = WWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdAccountRoute = WWorkspaceIdAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdAgentsRoute = WWorkspaceIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdChatRoute = WWorkspaceIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdConnectionsRoute = WWorkspaceIdConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdChatIndexRoute = WWorkspaceIdChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWorkspaceIdChatRoute,
} as any)
const WWorkspaceIdChatConversationIdRoute =
  WWorkspaceIdChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => WWorkspaceIdChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/login/code': typeof LoginCodeRoute
  '/login/mfa': typeof LoginMfaRoute
  '/w/$workspaceId': typeof WWorkspaceIdRouteWithChildren
  '/w/$workspaceId/account': typeof WWorkspaceIdAccountRoute
  '/w/$workspaceId/agents': typeof WWorkspaceIdAgentsRoute
  '/w/$workspaceId/chat': typeof WWorkspaceIdChatRouteWithChildren
  '/w/$workspaceId/connections': typeof WWorkspaceIdConnectionsRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/chat/$conversationId': typeof WWorkspaceIdChatConversationIdRoute
  '/w/$workspaceId/chat/': typeof WWorkspaceIdChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/login/code': typeof LoginCodeRoute
  '/login/mfa': typeof LoginMfaRoute
  '/w/$workspaceId/account': typeof WWorkspaceIdAccountRoute
  '/w/$workspaceId/agents': typeof WWorkspaceIdAgentsRoute
  '/w/$workspaceId/connections': typeof WWorkspaceIdConnectionsRoute
  '/w/$workspaceId': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/chat/$conversationId': typeof WWorkspaceIdChatConversationIdRoute
  '/w/$workspaceId/chat': typeof WWorkspaceIdChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/login_/code': typeof LoginCodeRoute
  '/login_/mfa': typeof LoginMfaRoute
  '/w/$workspaceId': typeof WWorkspaceIdRouteWithChildren
  '/w/$workspaceId/account': typeof WWorkspaceIdAccountRoute
  '/w/$workspaceId/agents': typeof WWorkspaceIdAgentsRoute
  '/w/$workspaceId/chat': typeof WWorkspaceIdChatRouteWithChildren
  '/w/$workspaceId/connections': typeof WWorkspaceIdConnectionsRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/chat/$conversationId': typeof WWorkspaceIdChatConversationIdRoute
  '/w/$workspaceId/chat/': typeof WWorkspaceIdChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/login/code'
    | '/login/mfa'
    | '/w/$workspaceId'
    | '/w/$workspaceId/account'
    | '/w/$workspaceId/agents'
    | '/w/$workspaceId/chat'
    | '/w/$workspaceId/connections'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/chat/$conversationId'
    | '/w/$workspaceId/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/login/code'
    | '/login/mfa'
    | '/w/$workspaceId/account'
    | '/w/$workspaceId/agents'
    | '/w/$workspaceId/connections'
    | '/w/$workspaceId'
    | '/w/$workspaceId/chat/$conversationId'
    | '/w/$workspaceId/chat'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/login_/code'
    | '/login_/mfa'
    | '/w/$workspaceId'
    | '/w/$workspaceId/account'
    | '/w/$workspaceId/agents'
    | '/w/$workspaceId/chat'
    | '/w/$workspaceId/connections'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/chat/$conversationId'
    | '/w/$workspaceId/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  LoginCodeRoute: typeof LoginCodeRoute
  LoginMfaRoute: typeof LoginMfaRoute
  WWorkspaceIdRoute: typeof WWorkspaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/code': {
      id: '/login_/code'
      path: '/login/code'
      fullPath: '/login/code'
      preLoaderRoute: typeof LoginCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/mfa': {
      id: '/login_/mfa'
      path: '/login/mfa'
      fullPath: '/login/mfa'
      preLoaderRoute: typeof LoginMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId': {
      id: '/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof WWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId/': {
      id: '/w/$workspaceId/'
      path: '/'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof WWorkspaceIdIndexRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/account': {
      id: '/w/$workspaceId/account'
      path: '/account'
      fullPath: '/w/$workspaceId/account'
      preLoaderRoute: typeof WWorkspaceIdAccountRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/agents': {
      id: '/w/$workspaceId/agents'
      path: '/agents'
      fullPath: '/w/$workspaceId/agents'
      preLoaderRoute: typeof WWorkspaceIdAgentsRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/chat': {
      id: '/w/$workspaceId/chat'
      path: '/chat'
      fullPath: '/w/$workspaceId/chat'
      preLoaderRoute: typeof WWorkspaceIdChatRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/connections': {
      id: '/w/$workspaceId/connections'
      path: '/connections'
      fullPath: '/w/$workspaceId/connections'
      preLoaderRoute: typeof WWorkspaceIdConnectionsRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/chat/': {
      id: '/w/$workspaceId/chat/'
      path: '/'
      fullPath: '/w/$workspaceId/chat/'
      preLoaderRoute: typeof WWorkspaceIdChatIndexRouteImport
      parentRoute: typeof WWorkspaceIdChatRoute
    }
    '/w/$workspaceId/chat/$conversationId': {
      id: '/w/$workspaceId/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/w/$workspaceId/chat/$conversationId'
      preLoaderRoute: typeof WWorkspaceIdChatConversationIdRouteImport
      parentRoute: typeof WWorkspaceIdChatRoute
    }
  }
}

interface WWorkspaceIdChatRouteChildren {
  WWorkspaceIdChatConversationIdRoute: typeof WWorkspaceIdChatConversationIdRoute
  WWorkspaceIdChatIndexRoute: typeof WWorkspaceIdChatIndexRoute
}

const WWorkspaceIdChatRouteChildren: WWorkspaceIdChatRouteChildren = {
  WWorkspaceIdChatConversationIdRoute: WWorkspaceIdChatConversationIdRoute,
  WWorkspaceIdChatIndexRoute: WWorkspaceIdChatIndexRoute,
}

const WWorkspaceIdChatRouteWithChildren =
  WWorkspaceIdChatRoute._addFileChildren(WWorkspaceIdChatRouteChildren)

interface WWorkspaceIdRouteChildren {
  WWorkspaceIdAccountRoute: typeof WWorkspaceIdAccountRoute
  WWorkspaceIdAgentsRoute: typeof WWorkspaceIdAgentsRoute
  WWorkspaceIdChatRoute: typeof WWorkspaceIdChatRouteWithChildren
  WWorkspaceIdConnectionsRoute: typeof WWorkspaceIdConnectionsRoute
  WWorkspaceIdIndexRoute: typeof WWorkspaceIdIndexRoute
}

const WWorkspaceIdRouteChildren: WWorkspaceIdRouteChildren = {
  WWorkspaceIdAccountRoute: WWorkspaceIdAccountRoute,
  WWorkspaceIdAgentsRoute: WWorkspaceIdAgentsRoute,
  WWorkspaceIdChatRoute: WWorkspaceIdChatRouteWithChildren,
  WWorkspaceIdConnectionsRoute: WWorkspaceIdConnectionsRoute,
  WWorkspaceIdIndexRoute: WWorkspaceIdIndexRoute,
}

const WWorkspaceIdRouteWithChildren = WWorkspaceIdRoute._addFileChildren(
  WWorkspaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  LoginCodeRoute: LoginCodeRoute,
  LoginMfaRoute: LoginMfaRoute,
  WWorkspaceIdRoute: WWorkspaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
