"""Build the Minerva logo as flat, single-path SVG geometry.

The owl comes from design/logo/owl.svg (traced by trace.py); the name is MINERVA shaped from the
Archivo font. Both are flattened with boolean operations so every exported file is one plain path
with no masks, clip paths, strokes or fonts.

Usage (from the repository root):
  uv run --with fonttools --with skia-pathops --with uharfbuzz python design/logo/build.py <Archivo[wdth,wght].ttf>
Writes design/logo/geometry.json. Run design/logo/export.py afterwards.
"""

import json
import pathlib
import re
import sys

import pathops
import uharfbuzz as hb
from fontTools.pens.basePen import BasePen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.svgLib.path import parse_path
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

HERE = pathlib.Path(__file__).parent
FONT = pathlib.Path(sys.argv[1])

# The owl is scaled to 100 units tall, with its top left corner at the origin.
HEIGHT = 100

# --- the name: Archivo Expanded ExtraBold capitals, cap height 34 on baseline 70 ---
NAME, WDTH, WGHT, TRACK, CAP, BASELINE, NAME_GAP = "MINERVA", 125, 800, 0.03, 34, 70, 18


class _Pen(BasePen):
    """Rounds coordinates while drawing into an SVGPathPen."""

    def __init__(self, out, transform=(1, 0, 0, 1, 0, 0)):
        super().__init__(None)
        self.out = TransformPen(out, transform)

    def _moveTo(self, p): self.out.moveTo(p)
    def _lineTo(self, p): self.out.lineTo(p)
    def _curveToOne(self, a, b, c): self.out.curveTo(a, b, c)
    def _qCurveToOne(self, a, b): self.out.qCurveTo(a, b)
    def _closePath(self): self.out.closePath()


def to_d(path, transform=(1, 0, 0, 1, 0, 0)):
    pen = SVGPathPen(None, ntos=lambda v: f"{round(v, 2):g}")
    path.draw(_Pen(pen, transform))
    return pen.getCommands()


def bounds(path):
    pen = BoundsPen(None)
    path.draw(pen)
    return pen.bounds


def owl_path():
    """The traced owl, with even-odd holes turned into a plain filled path, 100 units tall."""
    d = re.search(r'\sd="([^"]+)"', (HERE / "owl.svg").read_text()).group(1)
    traced = pathops.Path(fillType=pathops.FillType.EVEN_ODD)
    parse_path(d, traced.getPen())
    traced = pathops.simplify(traced)
    x0, y0, _, y1 = bounds(traced)
    scale = HEIGHT / (y1 - y0)
    out = pathops.Path()
    traced.draw(TransformPen(out.getPen(), (scale, 0, 0, scale, -x0 * scale, -y0 * scale)))
    return pathops.simplify(out)


def name_path():
    font = TTFont(FONT)
    instance = instantiateVariableFont(font, {"wdth": WDTH, "wght": WGHT})
    glyphs = instance.getGlyphSet()
    cap = glyphs[instance.getBestCmap()[ord("H")]]
    cap_pen = BoundsPen(glyphs)
    cap.draw(cap_pen)
    scale = CAP / cap_pen.bounds[3]
    upm = instance["head"].unitsPerEm

    blob = hb.Blob.from_file_path(str(FONT))
    hb_font = hb.Font(hb.Face(blob))
    hb_font.set_variations({"wdth": WDTH, "wght": WGHT})
    buf = hb.Buffer()
    buf.add_str(NAME)
    buf.guess_segment_properties()
    hb.shape(hb_font, buf, {"kern": True})

    out, x = pathops.Path(), 0.0
    order = instance.getGlyphOrder()
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        glyph = pathops.Path()
        glyphs[order[info.codepoint]].draw(TransformPen(glyph.getPen(), (scale, 0, 0, -scale, x * scale, BASELINE)))
        out = pathops.op(out, pathops.simplify(glyph), pathops.PathOp.UNION)
        x += pos.x_advance + TRACK * upm
    return out


def main():
    owl = owl_path()
    name = name_path()

    _, _, ow, oh = bounds(owl)
    nx0, ny0, nx1, ny1 = bounds(name)
    # The name starts NAME_GAP units after the owl's right edge, measured to its ink.
    dx = ow + NAME_GAP - nx0

    geometry = {
        "note": "Generated by design/logo/build.py. Do not edit by hand.",
        "owl": {"viewBox": [0, 0, round(ow, 2), round(oh, 2)], "d": to_d(owl)},
        "name": {
            "viewBox": [0, round(ny0, 2), round(nx1 - nx0, 2), round(ny1 - ny0, 2)],
            "d": to_d(name, (1, 0, 0, 1, -nx0, 0)),
            "inLockup": to_d(name, (1, 0, 0, 1, dx, 0)),
        },
        "lockup": {"viewBox": [0, 0, round(nx1 + dx, 2), HEIGHT]},
    }
    (HERE / "geometry.json").write_text(json.dumps(geometry, indent=2) + "\n")
    print("lockup width", round(nx1 + dx, 2), "| name ink", [round(v, 2) for v in (nx0, ny0, nx1, ny1)], "| owl", [round(ow, 2), round(oh, 2)], "|", len(geometry["owl"]["d"]), "bytes")


main()
