"""Export the Minerva logo files from design/logo/geometry.json.

Usage (from the repository root): python3 design/logo/export.py <out dir>
Writes SVG, PNG and ICO files to <out dir>, the paths the frontend draws to
frontend/src/components/brand/logo-paths.ts, and the favicons in frontend/public/.
If ../landing-page exists, it also gets the logo and the favicons.
Needs rsvg-convert and magick.
"""

import json
import pathlib
import shutil
import subprocess
import sys

HERE = pathlib.Path(__file__).parent
ROOT = HERE.parents[1]
OUT = pathlib.Path(sys.argv[1])
G = json.loads((HERE / "geometry.json").read_text())

COLOURS = {"navy": "#15216a", "black": "#000000", "white": "#ffffff"}


def box(vb, pad=0):
    x, y, w, h = vb
    return [x - pad, y - pad, w + 2 * pad, h + 2 * pad]


def square(vb):
    """Centre a viewBox in a square, for icons."""
    x, y, w, h = vb
    s = max(w, h)
    return [x - (s - w) / 2, y - (s - h) / 2, s, s]


def svg(vb, d, fill, title="Minerva", style=""):
    v = " ".join(f"{round(n, 2):g}" for n in vb)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{v}" role="img" aria-label="{title}">'
            f"{style}<title>{title}</title><path fill=\"{fill}\" d=\"{d}\"/></svg>\n")


def write(rel, text):
    path = OUT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return path


def png(src, rel, width=None, height=None, background=None):
    dst = OUT / rel
    dst.parent.mkdir(parents=True, exist_ok=True)
    cmd = ["rsvg-convert", str(src), "-o", str(dst)]
    if width:
        cmd += ["-w", str(width)]
    if height:
        cmd += ["-h", str(height)]
    if background:
        cmd += ["-b", background]
    subprocess.run(cmd, check=True)
    return dst


lockup = f"{G['owl']['d']}{G['name']['inLockup']}"
FORMS = {
    # name: (folder, viewBox, path)
    "minerva-logo": ("logo", G["lockup"]["viewBox"], lockup),
    "minerva-mark": ("mark", G["owl"]["viewBox"], G["owl"]["d"]),
    "minerva-wordmark": ("wordmark", G["name"]["viewBox"], G["name"]["d"]),
}

if OUT.exists():
    for folder in ("logo", "mark", "wordmark", "icon", "png"):
        shutil.rmtree(OUT / folder, ignore_errors=True)

svgs = {}
for name, (folder, vb, d) in FORMS.items():
    for colour, fill in COLOURS.items():
        suffix = "" if colour == "navy" else f"-{colour}"
        svgs[name + suffix] = write(f"{folder}/{name}{suffix}.svg", svg(vb, d, fill))

# Icons: the owl centred in a square. The browser tab follows the system theme.
owl_square = square(G["owl"]["viewBox"])
adaptive = "<style>path{fill:#15216a}@media (prefers-color-scheme:dark){path{fill:#e1e7f8}}</style>"
write("icon/favicon.svg", svg(owl_square, G["owl"]["d"], "#15216a", style=adaptive))
owl_icon = write("icon/.owl-square.svg", svg(owl_square, G["owl"]["d"], "#15216a"))
sizes = [png(owl_icon, f"icon/.{n}.png", n, n) for n in (16, 32, 48)]
subprocess.run(["magick", *map(str, sizes), str(OUT / "icon/favicon.ico")], check=True)
# Home screens fill transparency with black, so these sit on white with room around the owl.
padded = write("icon/.padded.svg", svg(box(owl_square, 16), G["owl"]["d"], "#15216a"))
png(padded, "icon/apple-touch-icon.png", 180, 180, "#ffffff")
png(padded, "icon/icon-192.png", 192, 192, "#ffffff")
png(padded, "icon/icon-512.png", 512, 512, "#ffffff")
png(padded, "icon/minerva-mark-1024.png", 1024, 1024, "#ffffff")
for tmp in (OUT / "icon").glob(".*"):
    tmp.unlink()

# Raster copies for documents and slides, transparent background.
for colour in ("", "-white"):
    png(svgs[f"minerva-logo{colour}"], f"png/minerva-logo{colour}-1200.png", 1200)
    png(svgs[f"minerva-logo{colour}"], f"png/minerva-logo{colour}-2400.png", 2400)
    png(svgs[f"minerva-mark{colour}"], f"png/minerva-mark{colour}-512.png", height=512)

# The frontend draws the logo inline from these paths, in currentColor.
ts = ROOT / "frontend/src/components/brand/logo-paths.ts"
ts.parent.mkdir(parents=True, exist_ok=True)
ts.write_text(
    "// Generated by design/logo/export.py from design/logo/geometry.json. Do not edit by hand.\n\n"
    f"export const OWL = '{G['owl']['d']}'\n"
    f"export const OWL_VIEWBOX = '{' '.join(f'{round(n, 2):g}' for n in square(G['owl']['viewBox']))}'\n"
    f"export const NAME_IN_LOCKUP = '{G['name']['inLockup']}'\n"
    f"export const LOCKUP_WIDTH = {G['lockup']['viewBox'][2]}\n"
)
shutil.copy(OUT / "icon/favicon.svg", ROOT / "frontend/public/favicon.svg")
shutil.copy(OUT / "icon/favicon.ico", ROOT / "frontend/public/favicon.ico")
shutil.copy(OUT / "icon/apple-touch-icon.png", ROOT / "frontend/public/apple-touch-icon.png")

# The landing page, when it sits next to this repository, inlines the lockup in currentColor.
LANDING = ROOT.parent / "landing-page"
if LANDING.exists():
    (LANDING / "src/assets/minerva-logo.svg").write_text(svg(G["lockup"]["viewBox"], lockup, "currentColor"))
    for name in ("favicon.svg", "favicon.ico", "apple-touch-icon.png"):
        shutil.copy(OUT / "icon" / name, LANDING / "public" / name)
print(f"Wrote {sum(1 for p in OUT.rglob('*') if p.is_file())} files under {OUT}")
