# Generated by Django 6.1.1 on 2026-09-29 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('redirect_uri', models.CharField(max_length=500)),
                ('client_id', models.CharField(max_length=200)),
                ('secret_ciphertext', models.BinaryField()),
                ('secret_key_version', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'redirect_uri'), name='oauth_client_provider_redirect')],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('external_account_id', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('credentials_ciphertext', models.BinaryField()),
                ('credentials_key_version', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'provider', 'external_account_id'), name='connection_account_unique')],
            },
        ),
    ]
