# Generated by Django 6.1.1 on 2026-09-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='credentials_generation',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
