# Generated by Django 6.1.1 on 2026-10-07 10:51

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models

# Deleting blob rows, by any path (the sweep, a workspace's cascade), queues their objects for deletion and
# subtracts their sizes from the workspace counters, in the deleting transaction. Counters are updated in workspace
# order, so concurrent deletions take their locks in the same order. Not run by TRUNCATE.
BLOB_DELETED = """
CREATE FUNCTION files_blob_deleted() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    deleted record;
    counted bigint;
BEGIN
    INSERT INTO files_looseobject (key, delete_after, leases, deletions)
        SELECT storage_key, clock_timestamp(), 0, 0 FROM old_rows
        ON CONFLICT (key) DO NOTHING;
    FOR deleted IN
        SELECT workspace_id, sum(size) AS bytes FROM old_rows GROUP BY workspace_id ORDER BY workspace_id
    LOOP
        SELECT bytes INTO counted FROM files_workspacestorage WHERE workspace_id = deleted.workspace_id
            FOR UPDATE;
        -- Less than the blobs held: the counter drifted (files_reconcile corrects it).
        IF counted < deleted.bytes THEN
            RAISE WARNING 'files: the storage counter of workspace % is below its deleted blobs',
                deleted.workspace_id;
        END IF;
        UPDATE files_workspacestorage SET bytes = GREATEST(bytes - deleted.bytes, 0)
            WHERE workspace_id = deleted.workspace_id;
    END LOOP;
    RETURN NULL;
END
$$;
CREATE TRIGGER files_blob_deleted AFTER DELETE ON files_blob
    REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION files_blob_deleted();
"""

# What identifies a blob, and what a version holds, never changes: the sweep and the counters rely on it.
IMMUTABLE = """
CREATE FUNCTION files_blob_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF (NEW.workspace_id, NEW.sha256, NEW.size, NEW.storage_key)
        IS DISTINCT FROM (OLD.workspace_id, OLD.sha256, OLD.size, OLD.storage_key) THEN
        RAISE EXCEPTION 'A blob''s workspace, hash, size and storage key cannot change.';
    END IF;
    RETURN NEW;
END
$$;
CREATE TRIGGER files_blob_immutable BEFORE UPDATE OF workspace_id, sha256, size, storage_key ON files_blob
    FOR EACH ROW EXECUTE FUNCTION files_blob_immutable();

CREATE FUNCTION files_version_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF (NEW.workspace_id, NEW.conversation_id, NEW.entries, NEW.hashes, NEW.digest, NEW.size, NEW.file_count)
        IS DISTINCT FROM
        (OLD.workspace_id, OLD.conversation_id, OLD.entries, OLD.hashes, OLD.digest, OLD.size, OLD.file_count)
    THEN
        RAISE EXCEPTION 'A folder version''s contents cannot change.';
    END IF;
    RETURN NEW;
END
$$;
CREATE TRIGGER files_version_immutable
    BEFORE UPDATE OF workspace_id, conversation_id, entries, hashes, digest, size, file_count
    ON files_folderversion FOR EACH ROW EXECUTE FUNCTION files_version_immutable();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0002_initial'),
        ('runs', '0011_reasoning_delta'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LooseObject',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('delete_after', models.DateTimeField(db_index=True)),
                ('leases', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceStorage',
            fields=[
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='workspaces.workspace')),
                ('bytes', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('storage_key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('last_used_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='FolderVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('turn', 'Turn'), ('base', 'Base'), ('checkpoint', 'Checkpoint')], max_length=16)),
                ('attempt', models.PositiveIntegerField(blank=True, null=True)),
                ('entries', models.JSONField()),
                ('hashes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64))),
                ('digest', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('file_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_versions', to='conversations.conversation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.folderversion')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='runs.run')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='RunBlob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='files.blob')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='runs.run')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='blob',
            constraint=models.UniqueConstraint(fields=('workspace', 'sha256'), name='files_blob_workspace_sha256'),
        ),
        migrations.AddIndex(
            model_name='folderversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['hashes'], name='files_version_hashes'),
        ),
        migrations.AddIndex(
            model_name='folderversion',
            index=models.Index(condition=models.Q(('kind', 'checkpoint')), fields=['created_at'], name='files_version_checkpoints'),
        ),
        migrations.AddConstraint(
            model_name='runblob',
            constraint=models.UniqueConstraint(fields=('run', 'blob'), name='files_runblob_run_blob'),
        ),
        migrations.RunSQL(
            BLOB_DELETED,
            reverse_sql="DROP TRIGGER files_blob_deleted ON files_blob; DROP FUNCTION files_blob_deleted();",
        ),
        migrations.RunSQL(
            IMMUTABLE,
            reverse_sql=(
                "DROP TRIGGER files_blob_immutable ON files_blob; DROP FUNCTION files_blob_immutable();"
                " DROP TRIGGER files_version_immutable ON files_folderversion;"
                " DROP FUNCTION files_version_immutable();"
            ),
        ),
    ]
