// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { authorize, cancelRun, changeAccess, createAgent, createConversation, deleteAgent, deleteConnection, deleteConversation, getAccess, getAgent, getConversation, getRun, listAccessResources, listAgents, listConnections, listConnectors, listConversations, me, type Options, postMessage, reconnect, updateAgent } from '../sdk.gen';
import type { AuthorizeData, AuthorizeResponse, CancelRunData, CancelRunResponse, ChangeAccessData, ChangeAccessResponse, CreateAgentData, CreateAgentResponse, CreateConversationData, CreateConversationResponse, DeleteAgentData, DeleteAgentResponse, DeleteConnectionData, DeleteConnectionResponse, DeleteConversationData, DeleteConversationResponse, GetAccessData, GetAccessResponse, GetAgentData, GetAgentResponse, GetConversationData, GetConversationResponse, GetRunData, GetRunResponse, ListAccessResourcesData, ListAccessResourcesResponse, ListAgentsData, ListAgentsResponse, ListConnectionsData, ListConnectionsResponse, ListConnectorsData, ListConnectorsResponse, ListConversationsData, ListConversationsResponse, MeData, MeResponse, PostMessageData, PostMessageResponse, ReconnectData, ReconnectResponse, UpdateAgentData, UpdateAgentResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const meQueryKey = (options?: Options<MeData>) => createQueryKey('me', options);

/**
 * Me
 */
export const meOptions = (options?: Options<MeData>) => queryOptions<MeResponse, DefaultError, MeResponse, ReturnType<typeof meQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await me({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: meQueryKey(options)
});

export const listAgentsQueryKey = (options: Options<ListAgentsData>) => createQueryKey('listAgents', options);

/**
 * List Agents
 */
export const listAgentsOptions = (options: Options<ListAgentsData>) => queryOptions<ListAgentsResponse, DefaultError, ListAgentsResponse, ReturnType<typeof listAgentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAgents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAgentsQueryKey(options)
});

/**
 * Create Agent
 */
export const createAgentMutation = (options?: Partial<Options<CreateAgentData>>): UseMutationOptions<CreateAgentResponse, DefaultError, Options<CreateAgentData>> => {
    const mutationOptions: UseMutationOptions<CreateAgentResponse, DefaultError, Options<CreateAgentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createAgent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Agent
 */
export const deleteAgentMutation = (options?: Partial<Options<DeleteAgentData>>): UseMutationOptions<DeleteAgentResponse, DefaultError, Options<DeleteAgentData>> => {
    const mutationOptions: UseMutationOptions<DeleteAgentResponse, DefaultError, Options<DeleteAgentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAgent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAgentQueryKey = (options: Options<GetAgentData>) => createQueryKey('getAgent', options);

/**
 * Get Agent
 */
export const getAgentOptions = (options: Options<GetAgentData>) => queryOptions<GetAgentResponse, DefaultError, GetAgentResponse, ReturnType<typeof getAgentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAgent({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAgentQueryKey(options)
});

/**
 * Update Agent
 */
export const updateAgentMutation = (options?: Partial<Options<UpdateAgentData>>): UseMutationOptions<UpdateAgentResponse, DefaultError, Options<UpdateAgentData>> => {
    const mutationOptions: UseMutationOptions<UpdateAgentResponse, DefaultError, Options<UpdateAgentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateAgent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listConnectionsQueryKey = (options: Options<ListConnectionsData>) => createQueryKey('listConnections', options);

/**
 * List Connections
 */
export const listConnectionsOptions = (options: Options<ListConnectionsData>) => queryOptions<ListConnectionsResponse, DefaultError, ListConnectionsResponse, ReturnType<typeof listConnectionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listConnections({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listConnectionsQueryKey(options)
});

/**
 * Delete Connection
 */
export const deleteConnectionMutation = (options?: Partial<Options<DeleteConnectionData>>): UseMutationOptions<DeleteConnectionResponse, DefaultError, Options<DeleteConnectionData>> => {
    const mutationOptions: UseMutationOptions<DeleteConnectionResponse, DefaultError, Options<DeleteConnectionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteConnection({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAccessQueryKey = (options: Options<GetAccessData>) => createQueryKey('getAccess', options);

/**
 * Get Access
 *
 * What the user allows on this connection. Does not call the provider.
 */
export const getAccessOptions = (options: Options<GetAccessData>) => queryOptions<GetAccessResponse, DefaultError, GetAccessResponse, ReturnType<typeof getAccessQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAccess({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAccessQueryKey(options)
});

/**
 * Change Access
 *
 * Changes what the user allows on some resources, all or nothing. Revokes the user's active runs.
 */
export const changeAccessMutation = (options?: Partial<Options<ChangeAccessData>>): UseMutationOptions<ChangeAccessResponse, DefaultError, Options<ChangeAccessData>> => {
    const mutationOptions: UseMutationOptions<ChangeAccessResponse, DefaultError, Options<ChangeAccessData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await changeAccess({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listAccessResourcesQueryKey = (options: Options<ListAccessResourcesData>) => createQueryKey('listAccessResources', options);

/**
 * List Access Resources
 *
 * One page of resources the connected account can see, with what the user allows on each.
 */
export const listAccessResourcesOptions = (options: Options<ListAccessResourcesData>) => queryOptions<ListAccessResourcesResponse, DefaultError, ListAccessResourcesResponse, ReturnType<typeof listAccessResourcesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAccessResources({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAccessResourcesQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listAccessResourcesInfiniteQueryKey = (options: Options<ListAccessResourcesData>): QueryKey<Options<ListAccessResourcesData>> => createQueryKey('listAccessResources', options, true);

/**
 * List Access Resources
 *
 * One page of resources the connected account can see, with what the user allows on each.
 */
export const listAccessResourcesInfiniteOptions = (options: Options<ListAccessResourcesData>) => {
    const opts = infiniteQueryOptions<ListAccessResourcesResponse, DefaultError, InfiniteData<ListAccessResourcesResponse>, QueryKey<Options<ListAccessResourcesData>>, string | null | Pick<QueryKey<Options<ListAccessResourcesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListAccessResourcesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    cursor: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listAccessResources({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listAccessResourcesInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Reconnect
 *
 * Reconnects the account, or grants the provider access that allowed actions still need.
 */
export const reconnectMutation = (options?: Partial<Options<ReconnectData>>): UseMutationOptions<ReconnectResponse, DefaultError, Options<ReconnectData>> => {
    const mutationOptions: UseMutationOptions<ReconnectResponse, DefaultError, Options<ReconnectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reconnect({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Authorize
 */
export const authorizeMutation = (options?: Partial<Options<AuthorizeData>>): UseMutationOptions<AuthorizeResponse, DefaultError, Options<AuthorizeData>> => {
    const mutationOptions: UseMutationOptions<AuthorizeResponse, DefaultError, Options<AuthorizeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authorize({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listConnectorsQueryKey = (options: Options<ListConnectorsData>) => createQueryKey('listConnectors', options);

/**
 * List Connectors
 */
export const listConnectorsOptions = (options: Options<ListConnectorsData>) => queryOptions<ListConnectorsResponse, DefaultError, ListConnectorsResponse, ReturnType<typeof listConnectorsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listConnectors({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listConnectorsQueryKey(options)
});

export const listConversationsQueryKey = (options: Options<ListConversationsData>) => createQueryKey('listConversations', options);

/**
 * List Conversations
 */
export const listConversationsOptions = (options: Options<ListConversationsData>) => queryOptions<ListConversationsResponse, DefaultError, ListConversationsResponse, ReturnType<typeof listConversationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listConversations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listConversationsQueryKey(options)
});

/**
 * Create Conversation
 */
export const createConversationMutation = (options?: Partial<Options<CreateConversationData>>): UseMutationOptions<CreateConversationResponse, DefaultError, Options<CreateConversationData>> => {
    const mutationOptions: UseMutationOptions<CreateConversationResponse, DefaultError, Options<CreateConversationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createConversation({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Conversation
 */
export const deleteConversationMutation = (options?: Partial<Options<DeleteConversationData>>): UseMutationOptions<DeleteConversationResponse, DefaultError, Options<DeleteConversationData>> => {
    const mutationOptions: UseMutationOptions<DeleteConversationResponse, DefaultError, Options<DeleteConversationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteConversation({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getConversationQueryKey = (options: Options<GetConversationData>) => createQueryKey('getConversation', options);

/**
 * Get Conversation
 */
export const getConversationOptions = (options: Options<GetConversationData>) => queryOptions<GetConversationResponse, DefaultError, GetConversationResponse, ReturnType<typeof getConversationQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getConversation({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getConversationQueryKey(options)
});

/**
 * Post Message
 */
export const postMessageMutation = (options?: Partial<Options<PostMessageData>>): UseMutationOptions<PostMessageResponse, DefaultError, Options<PostMessageData>> => {
    const mutationOptions: UseMutationOptions<PostMessageResponse, DefaultError, Options<PostMessageData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postMessage({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRunQueryKey = (options: Options<GetRunData>) => createQueryKey('getRun', options);

/**
 * Get Run
 */
export const getRunOptions = (options: Options<GetRunData>) => queryOptions<GetRunResponse, DefaultError, GetRunResponse, ReturnType<typeof getRunQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRun({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRunQueryKey(options)
});

/**
 * Cancel Run
 */
export const cancelRunMutation = (options?: Partial<Options<CancelRunData>>): UseMutationOptions<CancelRunResponse, DefaultError, Options<CancelRunData>> => {
    const mutationOptions: UseMutationOptions<CancelRunResponse, DefaultError, Options<CancelRunData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await cancelRun({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
